services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      POSTGRES_DB: obr_mosmit
      POSTGRES_PASSWORD: obr_mosmit
      POSTGRES_USER: obr_mosmit
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U obr_mosmit -d obr_mosmit"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
