package ru.obr_mosmit.site.web;
import java.util.*;import org.springframework.http.ResponseEntity;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import ru.obr_mosmit.site.document.*;import ru.obr_mosmit.site.media.MediaStorageService;
@RestController public class DocumentApiController{
 private final SiteDocumentRepository documents;private final DocumentSectionRepository sections;private final MediaStorageService storage;
 public DocumentApiController(SiteDocumentRepository d,DocumentSectionRepository s,MediaStorageService storage){documents=d;sections=s;this.storage=storage;}
 @GetMapping("/api/documents") List<DocumentDto> all(){return documents.findAllByPublishedTrueOrderBySortOrderAscTitleAsc().stream().map(this::dto).toList();}
 @GetMapping("/api/documents/{id}") ResponseEntity<DocumentDetailsDto> one(@PathVariable Long id){return documents.findById(id).filter(SiteDocument::isPublished).map(d->ResponseEntity.ok(details(d))).orElseGet(()->ResponseEntity.notFound().build());}
 @GetMapping("/api/document-sections") List<SectionDto> publicSections(){return sections.findAllByOrderBySortOrderAscTitleAsc().stream().map(this::sectionDto).toList();}
 @GetMapping("/api/admin/documents") List<AdminDocumentDto> adminDocuments(){return documents.findAllByOrderBySortOrderAscTitleAsc().stream().map(this::adminDto).toList();}
 @PostMapping("/api/admin/documents") AdminDocumentDto save(@RequestBody DocumentRequest r){var d=r.id()==null?new SiteDocument():documents.findById(r.id()).orElseThrow();d.setTitle(r.title());d.setSummary(value(r.summary()));d.setContent(value(r.content()));d.setSortOrder(r.sortOrder());d.setPublished(r.published());d.setSection(r.sectionId()==null?null:sections.findById(r.sectionId()).orElseThrow());d.setCategory(d.getSection()==null?"Документы":d.getSection().getTitle());d.setAttachments(value(r.attachments()));if(r.id()==null){var token=UUID.randomUUID().toString();d.setSlug("document-"+token);d.setSourceUrl("/admin/documents/"+token);}return adminDto(documents.save(d));}
 @PostMapping("/api/admin/documents/{id}/files") AdminDocumentDto upload(@PathVariable Long id,@RequestParam("files")MultipartFile[] files){var d=documents.findById(id).orElseThrow();var rows=new ArrayList<String>();if(d.getAttachments()!=null&&!d.getAttachments().isBlank())rows.addAll(Arrays.asList(d.getAttachments().split("\n")));for(var f:files)rows.add(Objects.requireNonNullElse(f.getOriginalFilename(),"Файл")+"|"+storage.storeDocument(f));d.setAttachments(String.join("\n",rows));return adminDto(documents.save(d));}
 @DeleteMapping("/api/admin/documents/{id}") void delete(@PathVariable Long id){documents.deleteById(id);}
 @GetMapping("/api/admin/document-sections") List<SectionDto> adminSections(){return publicSections();}
 @PostMapping("/api/admin/document-sections") SectionDto saveSection(@RequestBody SectionRequest r){var s=r.id()==null?new DocumentSection():sections.findById(r.id()).orElseThrow();s.setTitle(r.title());s.setSortOrder(r.sortOrder());s.setParent(r.parentId()==null?null:sections.findById(r.parentId()).orElseThrow());if(r.id()==null)s.setSlug("section-"+UUID.randomUUID());return sectionDto(sections.save(s));}
 @DeleteMapping("/api/admin/document-sections/{id}") void deleteSection(@PathVariable Long id){sections.deleteById(id);}
 private String value(String v){return v==null?"":v.trim();}private String sectionTitle(SiteDocument d){return d.getSection()==null?Objects.requireNonNullElse(d.getCategory(),"Документы"):d.getSection().getTitle();}
 private DocumentDto dto(SiteDocument d){return new DocumentDto(String.valueOf(d.getId()),d.getTitle(),sectionTitle(d),d.getSummary(),attachments(d),d.getSourceUrl(),d.getSection()==null?null:d.getSection().getId());}
 private DocumentDetailsDto details(SiteDocument d){return new DocumentDetailsDto(String.valueOf(d.getId()),d.getTitle(),sectionTitle(d),d.getContent(),attachments(d));}
 private AdminDocumentDto adminDto(SiteDocument d){return new AdminDocumentDto(d.getId(),d.getTitle(),d.getSummary(),d.getContent(),d.getSection()==null?null:d.getSection().getId(),d.getSortOrder(),d.isPublished(),d.getAttachments());}
 private List<AttachmentDto> attachments(SiteDocument d){List<AttachmentDto> files=new ArrayList<>();if(d.getAttachments()!=null&&!d.getAttachments().isBlank())for(String row:d.getAttachments().split("\n")){String[] p=row.split("\\|",2);if(p.length==2)files.add(new AttachmentDto(p[0],p[1]));}return files;}
 private SectionDto sectionDto(DocumentSection s){return new SectionDto(s.getId(),s.getTitle(),s.getSlug(),s.getParent()==null?null:s.getParent().getId(),s.getSortOrder());}
 public record DocumentDto(String id,String title,String category,String summary,List<AttachmentDto> attachments,String sourceUrl,Long sectionId){}public record AttachmentDto(String title,String url){}public record DocumentDetailsDto(String id,String title,String category,String content,List<AttachmentDto> attachments){}public record AdminDocumentDto(Long id,String title,String summary,String content,Long sectionId,int sortOrder,boolean published,String attachments){}record DocumentRequest(Long id,String title,String summary,String content,Long sectionId,int sortOrder,boolean published,String attachments){}public record SectionDto(Long id,String title,String slug,Long parentId,int sortOrder){}record SectionRequest(Long id,String title,Long parentId,int sortOrder){}
}
