import { useEffect,useState } from 'react';import type { FormEvent } from 'react';
type Contacts={id:number;city:string;address:string;publicEmail:string;publicEmailNote:string;chairmanRole:string;chairmanName:string;chairmanEmail:string;assistantRole:string;assistantName:string;assistantEmail:string}
const clergyTitles=['Протоиерей','Иерей','Священник','Диакон','Протодиакон','Чтец','Монах','Иеромонах','Архимандрит','Игумен','Епископ','Митрополит']
const splitPersonName=(value='')=>{const clean=value.trim();const title=clergyTitles.find(item=>clean.toLocaleLowerCase('ru').startsWith(item.toLocaleLowerCase('ru')+' '));return title?{title,name:clean.slice(title.length).trim()}:{title:'',name:clean}}
export function AdminContactsPage(){const[data,setData]=useState<Contacts|null>(null),[message,setMessage]=useState('');useEffect(()=>{fetch('/api/contacts').then(r=>r.json()).then(setData)},[]);const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));const chairmanName=[values.chairmanTitle,values.chairmanName].filter(Boolean).join(' ').trim();const assistantName=[values.assistantTitle,values.assistantName].filter(Boolean).join(' ').trim();delete values.chairmanTitle;delete values.assistantTitle;const r=await fetch('/api/admin/contacts',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,chairmanName,assistantName,id:1})});if(r.ok){setData(await r.json());setMessage('Контакты сохранены')}};if(!data)return <p>Загрузка…</p>;const chairman=splitPersonName(data.chairmanName);const assistant=splitPersonName(data.assistantName);return <><header className="page-header"><div><span className="overline">Содержание сайта</span><h1>Контакты</h1><p>Адрес, общая почта и ответственные лица.</p></div></header><form className="surface admin-content-form admin-contacts-form" onSubmit={save}>
<section className="admin-form-section"><div className="admin-form-section-heading"><div><span className="admin-section-kicker">Основная информация</span><h2>Контакты отдела</h2></div></div><div className="admin-contact-main-grid"><label><span>Город</span><input name="city" defaultValue={data.city} required/></label><label><span>Адрес</span><input name="address" defaultValue={data.address} required/></label><label><span>Общая электронная почта</span><input name="publicEmail" type="email" defaultValue={data.publicEmail} required/></label><label><span>Пояснение к почте</span><input name="publicEmailNote" defaultValue={data.publicEmailNote}/></label></div></section>
<section className="admin-form-section admin-leadership-section"><div className="admin-form-section-heading"><div><span className="admin-section-kicker">Ответственные лица</span><h2>Руководство</h2></div></div><div className="admin-leadership-grid">
<div className="admin-person-card"><div className="admin-person-card-head"><span className="admin-person-index">01</span><div><strong>Руководитель</strong><small>Основное ответственное лицо</small></div></div><div className="admin-person-fields"><label><span>Роль в отделе</span><input name="chairmanRole" defaultValue={data.chairmanRole} placeholder="Председатель отдела"/></label><label><span>Сан / звание</span><input name="chairmanTitle" defaultValue={chairman.title} placeholder="Протоиерей"/></label><label><span>Имя</span><input name="chairmanName" defaultValue={chairman.name} placeholder="Сергий Якимов"/></label><label><span>Электронная почта</span><input name="chairmanEmail" type="email" defaultValue={data.chairmanEmail}/></label></div></div>
<div className="admin-person-card"><div className="admin-person-card-head"><span className="admin-person-index">02</span><div><strong>Помощник</strong><small>Второе ответственное лицо</small></div></div><div className="admin-person-fields"><label><span>Роль в отделе</span><input name="assistantRole" defaultValue={data.assistantRole} placeholder="Помощник председателя"/></label><label><span>Сан / звание</span><input name="assistantTitle" defaultValue={assistant.title} placeholder="Чтец"/></label><label><span>Имя</span><input name="assistantName" defaultValue={assistant.name} placeholder="Николай Казинов"/></label><label><span>Электронная почта</span><input name="assistantEmail" type="email" defaultValue={data.assistantEmail}/></label></div></div>
</div></section>{message&&<p className="form-notice">{message}</p>}<div className="admin-form-actions"><button className="button primary">Сохранить контакты</button></div></form></>}
