import { useEffect,useState } from 'react'
import type { FormEvent } from 'react'
import { CoverUploader,MediaGalleryUploader } from '../components/MediaUploaders'
import { Pagination } from '../components/Pagination'
type Course={id?:number;title:string;description:string;published:boolean;cover?:string;gallery?:string[]}
const json=async(url:string,options?:RequestInit)=>{const r=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json'},...options});if(!r.ok)throw new Error(await r.text()||'Ошибка');return r.status===204?null:r.json()}
export function AdminCoursesPage(){
 const[items,setItems]=useState<Course[]>([]),[search,setSearch]=useState(''),[page,setPage]=useState(1),[editing,setEditing]=useState<Course|null>(null),[error,setError]=useState('')
 const load=()=>json('/api/admin/courses').then(setItems).catch(e=>setError(e.message));useEffect(()=>{load()},[])
 useEffect(()=>{setPage(1)},[search])
 const normalizedSearch=search.trim().toLocaleLowerCase('ru')
 const visibleItems=normalizedSearch?items.filter(x=>[x.title,x.description].some(value=>(value||'').toLocaleLowerCase('ru').includes(normalizedSearch))):items
 const pageSize=12,pageItems=visibleItems.slice((page-1)*pageSize,page*pageSize)
 const remove=async(x:Course)=>{if(!x.id||!confirm(`Удалить курс «${x.title}»?`))return;await json(`/api/admin/courses/${x.id}`,{method:'DELETE'});if(editing?.id===x.id)setEditing(null);load()}
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await json('/api/admin/courses',{method:'POST',body:JSON.stringify({...d,id:editing?.id,published:d.published==='on'})});setEditing(null);load()}
 return <><header className="page-header"><div><span className="overline">Управление</span><h1>Курсы</h1><p>Добавляйте образовательные курсы, описание, обложку и фотографии.</p></div><button className="button primary" onClick={()=>setEditing({title:'',description:'',published:false})}>+ Новый курс</button></header>{error&&<p className="form-error">{error}</p>}<div className="document-search"><div className="document-search-field"><span aria-hidden="true">⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Найти курс по названию или описанию" aria-label="Поиск курсов" />{search&&<button type="button" onClick={()=>setSearch('')} aria-label="Очистить поиск">×</button>}</div><small>{search?`Найдено: ${visibleItems.length}`:`Всего курсов: ${items.length}`}</small></div><section className="surface table-wrap"><table><thead><tr><th>Курс</th><th>Статус</th><th/></tr></thead><tbody>{pageItems.map(x=><tr key={x.id}><td><div className="competition-admin-title">{x.cover&&<img src={x.cover} alt=""/>}<span><b>{x.title}</b><small>{x.description}</small></span></div></td><td><span className={`badge ${x.published?'published':''}`}>{x.published?'Опубликован':'Черновик'}</span></td><td className="row-actions"><button className="text-button" onClick={()=>setEditing(x)}>Редактировать</button><button className="text-button danger" onClick={()=>remove(x)}>Удалить</button></td></tr>)}{visibleItems.length===0&&<tr><td colSpan={3} className="empty-search-result">Курсы не найдены. Попробуйте изменить запрос.</td></tr>}</tbody></table><Pagination page={page} totalItems={visibleItems.length} pageSize={pageSize} onPageChange={setPage} label="Курсы"/></section>{editing&&<div className="modal-backdrop"><form className="cabinet-form modal content-editor-modal" onSubmit={save}><h2>{editing.id?'Редактировать курс':'Новый курс'}</h2><label>Название<input name="title" defaultValue={editing.title} required/></label><label>Описание<textarea name="description" defaultValue={editing.description} rows={7} required/></label>{editing.id?<><label>Обложка<CoverUploader endpoint={`/api/admin/media/courses/${editing.id}`} image={editing.cover}/></label><label>Изображения<MediaGalleryUploader endpoint={`/api/admin/media/courses/${editing.id}/gallery`} images={editing.gallery}/></label></>:<p className="editor-hint">Сохраните курс, затем откройте его снова для загрузки обложки и изображений.</p>}<label className="check"><input name="published" type="checkbox" defaultChecked={editing.published}/> Опубликовать</label><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setEditing(null)}>Отмена</button><button className="button primary">Сохранить</button></div></form></div>}</>
}
