import { FormEvent, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'

type Competition={id:number;title:string;description?:string;deadline?:string}
type Result={trackingCode:string;participantName:string;competitionTitle:string;status:string}

export function CompetitionApplicationPage(){
 const{id}=useParams(),[competition,setCompetition]=useState<Competition|null>(null),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[sending,setSending]=useState(false)
 useEffect(()=>{fetch('/api/competitions').then(r=>r.json()).then((items:Competition[])=>setCompetition(items.find(x=>String(x.id)===id)||null)).catch(()=>setError('Не удалось загрузить конкурс.'))},[id])
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');setSending(true);const f=new FormData(e.currentTarget);const body=Object.fromEntries(f.entries());try{const r=await fetch('/api/competition-applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,competitionId:Number(id),consent:f.get('consent')==='on'})});if(!r.ok)throw new Error(await r.text()||'Не удалось отправить заявку');setResult(await r.json())}catch(err){setError(err instanceof Error?err.message:'Не удалось отправить заявку')}finally{setSending(false)}}
 if(result)return <main><section className="page-hero"><span className="eyebrow">Заявка отправлена</span><h1>Спасибо!</h1><p>Сохраните номер заявки — он понадобится для проверки статуса.</p></section><section className="public-section application-success"><span>Номер заявки</span><strong>{result.trackingCode}</strong><p>Мы получили заявку на конкурс «{result.competitionTitle}».</p><Link className="button primary" to={`/proverit-zayavku?code=${encodeURIComponent(result.trackingCode)}`}>Проверить статус</Link></section></main>
 return <main><section className="page-hero"><span className="eyebrow">Участие в конкурсе</span><h1>Подать заявку</h1><p>{competition?.title||'Заполните данные участника. После отправки вы получите номер заявки.'}</p></section><section className="public-section application-page"><Link className="article-back" to="/konkursy">← Вернуться к конкурсам</Link><form className="public-application-form" onSubmit={submit}><div className="application-form-heading"><h2>Данные участника</h2><p>Поля со звёздочкой обязательны.</p></div><label>ФИО участника *<input name="participantName" required maxLength={250}/></label><label>Электронная почта *<input name="email" type="email" required maxLength={320}/><small>На эту почту привязывается заявка.</small></label><label>Телефон<input name="phone" type="tel" maxLength={50} placeholder="+7 …"/></label><label>Школа / образовательная организация *<input name="schoolName" required maxLength={500}/></label><label>Класс / возраст<input name="ageGroup" maxLength={100}/></label><label className="application-wide">Дополнительная информация<textarea name="comment" rows={5}/></label><label className="application-consent application-wide"><input name="consent" type="checkbox" required/><span>Я согласен(на) на обработку указанных персональных данных для рассмотрения заявки на конкурс.</span></label>{error&&<p className="form-error application-wide">{error}</p>}<div className="application-wide form-actions"><button className="button primary" disabled={sending}>{sending?'Отправляем…':'Отправить заявку'}</button></div></form></section></main>
}
